# Generated by Django 6.0.3 on 2026-03-04 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('referencia_bancaria', models.CharField(max_length=50)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_divisa', models.DecimalField(decimal_places=2, help_text='Monto en moneda local', max_digits=15)),
                ('comentarios', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_local', models.CharField(max_length=10)),
                ('canon_mensual', models.DecimalField(decimal_places=2, help_text='Monto en USD', max_digits=10)),
                ('fecha_proximo_aumento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
