# Generated by Django 6.0.3 on 2026-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_tasacambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfilinquilino',
            name='fecha_proximo_aumento',
        ),
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('BS', 'Bolívares (Bs.)'), ('USD', 'Dólares ($)')], default='BS', max_length=3),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_reportado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que el inquilino escribe', max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_divisa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfilinquilino',
            name='canon_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
