# Generated by Django 6.0.3 on 2026-03-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_alter_tasacambio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={'verbose_name_plural': 'Tasas de Cambio'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='monto_divisa',
            new_name='monto_bolivares',
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_reportado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
